imports:
  - { resource: "forms.yml" }

services:
  catalog-promotion.processor:
    class: SnakeTn\CatalogPromotion\Promotion\Processor
    arguments:
      - "@=service('doctrine.orm.entity_manager').getRepository('CatalogPromotionPlugin:Promotion')"
      - '@sylius.repository.promotion'

  catalog-promotion.has-taxon-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasTaxonRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_taxon, label: sylius.form.promotion.promotion_rule.has_at_least_one_from_taxons , form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\HasTaxonConfigurationType}]

  catalog-promotion.has-option-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasOptionRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_option, label: sylius.form.promotion.promotion_rule.contains_option, form-type: SnakeTn\CatalogPromotion\Form\Type\Rule\HasOptionValueConfigurationType}]

  catalog-promotion.has-product-rule-checker:
    class: SnakeTn\CatalogPromotion\Promotion\Checker\Rule\HasProductRuleChecker
    tags: [{name: catalog-promotion.rule-checker, type: has_product, label: sylius.form.promotion.promotion_rule.contains_product, form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\ContainsProductConfigurationType}]

  catalog-promotion.fixed-discount-action-executor:
    class: SnakeTn\CatalogPromotion\Promotion\Action\FixedDiscountPromotionActionExecutor
    arguments:
      - "@catalog-promotion.channel-pricing-promotion-applicator"
    tags: [{name: catalog-promotion.action-executor, type: fixed_discount, label: sylius.form.promotion.promotion_action.fixed_discount, form-type: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Action\ChannelBasedFixedDiscountConfigurationType}]

  catalog-promotion.percentage-discount-action-executor:
    class: SnakeTn\CatalogPromotion\Promotion\Action\PercentageDiscountPromotionActionExecutor
    arguments:
      - "@catalog-promotion.channel-pricing-promotion-applicator"
    tags: [{name: catalog-promotion.action-executor, type: percentage_discount, label: sylius.form.promotion.promotion_action.percentage_discount, form-type: Sylius\Bundle\PromotionBundle\Form\Type\Action\PercentageDiscountConfigurationType}]

  catalog-promotion.registry_promotion_rule_checker:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      - SnakeTn\CatalogPromotion\Promotion\Checker\Rule\RuleCheckerInterface
      - rule checker

  catalog-promotion.registry_promotion_action_executor:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      - SnakeTn\CatalogPromotion\Promotion\Action\ActionExecutorInterface
      - action executor

  catalog-promotion.form_registry.promotion_rule_checker:
    class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  catalog-promotion.form_registry.promotion_action_executor:
    class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  catalog-promotion.channel-pricing-promotion-applicator:
    class: SnakeTn\CatalogPromotion\Promotion\Applicator\ChannelPricingPromotionApplicator

  sylius.calculator.product_variant_price:
    class: SnakeTn\CatalogPromotion\Promotion\ProductVariantPriceCalculator
    arguments:
      - '@catalog-promotion.processor'

  catalog-promotion.admin.menu_builder:
    class: SnakeTn\CatalogPromotion\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  catalog-promotion.form.type.promotion_rule_choice:
    class: SnakeTn\CatalogPromotion\Form\Type\PromotionRuleChoiceType
    arguments: ['%catalog-promotion.promotion_rules%']
    tags:
      - { name: form.type}

  catalog-promotion.form.type.promotion_action_choice:
    class: SnakeTn\CatalogPromotion\Form\Type\PromotionActionChoiceType
    arguments: ['%catalog-promotion.promotion_actions%']
    tags:
      - { name: form.type}
